name: Run tests

on: push

jobs:
  run-tests:
    name: Run tests with latest Bempp
    runs-on: ubuntu-latest
    container: bempp/bempp-cl-with-dolfinx:latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          apt-get update
          apt-get -y install jupyter
          pip3 install plotly
        name: Install requirements
      - run: python3 -m pytest .test
        name: Run tests
